# docker-compose up
# docker-compose down

# to force delete the volume, and start from scratch
# docker-compose up --force-recreate --build
# docker-compose down --volumes --remove-orphans

# requires docker engine 17.06.0+
version: '3.8'
services:
  postgres:
    image: postgres:13.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
